name: Deploy (luna web)

on:
  push:
    branches:
      - master
jobs:
  deploy-dev:
    name: deploy-dev
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Deploy to dev
      - run: npm install --legacy-peer-deps
      - run: npx @serverless/cloud deploy dev
      # - run: npm run cloud:build
      # - run: npm run deploy
  deploy-test:
    name: deploy-test
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    environment: production
    needs: deploy-dev
    steps:
      - uses: trstringer/manual-approval@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: luna-team
      - name: Deploy to test
        run: npm install --legacy-peer-deps
        run: npx @serverless/cloud deploy test
