name: Deploy (luna web)

on:
  push:
    branches:
      - master
jobs:
  deploy-dev:
    name: deploy-dev
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install --legacy-peer-deps
      - run: npx @serverless/cloud deploy dev
  # deploy-prod:
  #   name: deploy-prod
  #   runs-on: ubuntu-latest
  #   needs: deploy-dev
  #   steps:
  #     - uses: trstringer/manual-approval@v1
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: fannymartensson
  #     - name: Deploy to production
  #       run: npm install --legacy-peer-deps
